export interface Currency {
  code: string;
  name: string;
  flag: string;
  symbol: string;
}

export const CURRENCIES: Currency[] = [
  // Major
  { code: "USD", name: "US Dollar", flag: "🇺🇸", symbol: "$" },
  { code: "EUR", name: "Euro", flag: "🇪🇺", symbol: "€" },
  { code: "GBP", name: "British Pound", flag: "🇬🇧", symbol: "£" },
  { code: "JPY", name: "Japanese Yen", flag: "🇯🇵", symbol: "¥" },
  { code: "CHF", name: "Swiss Franc", flag: "🇨🇭", symbol: "Fr" },
  { code: "CAD", name: "Canadian Dollar", flag: "🇨🇦", symbol: "$" },
  { code: "AUD", name: "Australian Dollar", flag: "🇦🇺", symbol: "$" },
  { code: "NZD", name: "New Zealand Dollar", flag: "🇳🇿", symbol: "$" },
  { code: "CNY", name: "Chinese Yuan", flag: "🇨🇳", symbol: "¥" },
  { code: "HKD", name: "Hong Kong Dollar", flag: "🇭🇰", symbol: "$" },
  { code: "SGD", name: "Singapore Dollar", flag: "🇸🇬", symbol: "$" },
  { code: "INR", name: "Indian Rupee", flag: "🇮🇳", symbol: "₹" },
  { code: "KRW", name: "South Korean Won", flag: "🇰🇷", symbol: "₩" },
  { code: "TWD", name: "Taiwan Dollar", flag: "🇹🇼", symbol: "NT$" },

  // Arab World
  { code: "AED", name: "UAE Dirham", flag: "🇦🇪", symbol: "د.إ" },
  { code: "SAR", name: "Saudi Riyal", flag: "🇸🇦", symbol: "﷼" },
  { code: "QAR", name: "Qatari Riyal", flag: "🇶🇦", symbol: "ر.ق" },
  { code: "KWD", name: "Kuwaiti Dinar", flag: "🇰🇼", symbol: "د.ك" },
  { code: "BHD", name: "Bahraini Dinar", flag: "🇧🇭", symbol: "ب.د" },
  { code: "OMR", name: "Omani Rial", flag: "🇴🇲", symbol: "ر.ع." },
  { code: "JOD", name: "Jordanian Dinar", flag: "🇯🇴", symbol: "د.ا" },
  { code: "LBP", name: "Lebanese Pound", flag: "🇱🇧", symbol: "ل.ل" },
  { code: "EGP", name: "Egyptian Pound", flag: "🇪🇬", symbol: "ج.م" },
  { code: "IQD", name: "Iraqi Dinar", flag: "🇮🇶", symbol: "ع.د" },
  { code: "SYP", name: "Syrian Pound", flag: "🇸🇾", symbol: "ل.س" },
  { code: "YER", name: "Yemeni Rial", flag: "🇾🇪", symbol: "﷼" },
  { code: "MAD", name: "Moroccan Dirham", flag: "🇲🇦", symbol: "د.م." },
  { code: "DZD", name: "Algerian Dinar", flag: "🇩🇿", symbol: "د.ج" },
  { code: "TND", name: "Tunisian Dinar", flag: "🇹🇳", symbol: "د.ت" },
  { code: "LYD", name: "Libyan Dinar", flag: "🇱🇾", symbol: "ل.د" },
  { code: "SDG", name: "Sudanese Pound", flag: "🇸🇩", symbol: "ج.س." },
  { code: "SOS", name: "Somali Shilling", flag: "🇸🇴", symbol: "Sh" },
  { code: "DJF", name: "Djiboutian Franc", flag: "🇩🇯", symbol: "Fdj" },
  { code: "KMF", name: "Comorian Franc", flag: "🇰🇲", symbol: "CF" },
  { code: "MRU", name: "Mauritanian Ouguiya", flag: "🇲🇷", symbol: "UM" },

  // Europe
  { code: "SEK", name: "Swedish Krona", flag: "🇸🇪", symbol: "kr" },
  { code: "NOK", name: "Norwegian Krone", flag: "🇳🇴", symbol: "kr" },
  { code: "DKK", name: "Danish Krone", flag: "🇩🇰", symbol: "kr" },
  { code: "ISK", name: "Icelandic Krona", flag: "🇮🇸", symbol: "kr" },
  { code: "PLN", name: "Polish Zloty", flag: "🇵🇱", symbol: "zł" },
  { code: "CZK", name: "Czech Koruna", flag: "🇨🇿", symbol: "Kč" },
  { code: "HUF", name: "Hungarian Forint", flag: "🇭🇺", symbol: "Ft" },
  { code: "RON", name: "Romanian Leu", flag: "🇷🇴", symbol: "lei" },
  { code: "BGN", name: "Bulgarian Lev", flag: "🇧🇬", symbol: "лв" },
  { code: "HRK", name: "Croatian Kuna", flag: "🇭🇷", symbol: "kn" },
  { code: "RSD", name: "Serbian Dinar", flag: "🇷🇸", symbol: "дин" },
  { code: "MKD", name: "Macedonian Denar", flag: "🇲🇰", symbol: "ден" },
  { code: "ALL", name: "Albanian Lek", flag: "🇦🇱", symbol: "L" },
  { code: "BAM", name: "Bosnian Mark", flag: "🇧🇦", symbol: "KM" },
  { code: "MDL", name: "Moldovan Leu", flag: "🇲🇩", symbol: "L" },
  { code: "UAH", name: "Ukrainian Hryvnia", flag: "🇺🇦", symbol: "₴" },
  { code: "BYN", name: "Belarusian Ruble", flag: "🇧🇾", symbol: "Br" },
  { code: "RUB", name: "Russian Ruble", flag: "🇷🇺", symbol: "₽" },
  { code: "TRY", name: "Turkish Lira", flag: "🇹🇷", symbol: "₺" },
  { code: "GEL", name: "Georgian Lari", flag: "🇬🇪", symbol: "₾" },
  { code: "AMD", name: "Armenian Dram", flag: "🇦🇲", symbol: "֏" },
  { code: "AZN", name: "Azerbaijani Manat", flag: "🇦🇿", symbol: "₼" },

  // Asia
  { code: "THB", name: "Thai Baht", flag: "🇹🇭", symbol: "฿" },
  { code: "IDR", name: "Indonesian Rupiah", flag: "🇮🇩", symbol: "Rp" },
  { code: "MYR", name: "Malaysian Ringgit", flag: "🇲🇾", symbol: "RM" },
  { code: "PHP", name: "Philippine Peso", flag: "🇵🇭", symbol: "₱" },
  { code: "VND", name: "Vietnamese Dong", flag: "🇻🇳", symbol: "₫" },
  { code: "PKR", name: "Pakistani Rupee", flag: "🇵🇰", symbol: "₨" },
  { code: "BDT", name: "Bangladeshi Taka", flag: "🇧🇩", symbol: "৳" },
  { code: "LKR", name: "Sri Lankan Rupee", flag: "🇱🇰", symbol: "Rs" },
  { code: "NPR", name: "Nepalese Rupee", flag: "🇳🇵", symbol: "₨" },
  { code: "MMK", name: "Myanmar Kyat", flag: "🇲🇲", symbol: "K" },
  { code: "KHR", name: "Cambodian Riel", flag: "🇰🇭", symbol: "៛" },
  { code: "LAK", name: "Lao Kip", flag: "🇱🇦", symbol: "₭" },
  { code: "MNT", name: "Mongolian Tugrik", flag: "🇲🇳", symbol: "₮" },
  { code: "KZT", name: "Kazakhstani Tenge", flag: "🇰🇿", symbol: "₸" },
  { code: "UZS", name: "Uzbekistani Som", flag: "🇺🇿", symbol: "сўм" },
  { code: "KGS", name: "Kyrgyzstani Som", flag: "🇰🇬", symbol: "с" },
  { code: "TJS", name: "Tajikistani Somoni", flag: "🇹🇯", symbol: "ЅМ" },
  { code: "TMT", name: "Turkmenistani Manat", flag: "🇹🇲", symbol: "T" },
  { code: "AFN", name: "Afghan Afghani", flag: "🇦🇫", symbol: "؋" },
  { code: "IRR", name: "Iranian Rial", flag: "🇮🇷", symbol: "﷼" },
  { code: "ILS", name: "Israeli Shekel", flag: "🇮🇱", symbol: "₪" },
  { code: "MOP", name: "Macanese Pataca", flag: "🇲🇴", symbol: "MOP$" },
  { code: "BND", name: "Brunei Dollar", flag: "🇧🇳", symbol: "$" },
  { code: "MVR", name: "Maldivian Rufiyaa", flag: "🇲🇻", symbol: "Rf" },
  { code: "BTN", name: "Bhutanese Ngultrum", flag: "🇧🇹", symbol: "Nu" },

  // Africa
  { code: "ZAR", name: "South African Rand", flag: "🇿🇦", symbol: "R" },
  { code: "NGN", name: "Nigerian Naira", flag: "🇳🇬", symbol: "₦" },
  { code: "KES", name: "Kenyan Shilling", flag: "🇰🇪", symbol: "KSh" },
  { code: "GHS", name: "Ghanaian Cedi", flag: "🇬🇭", symbol: "₵" },
  { code: "ETB", name: "Ethiopian Birr", flag: "🇪🇹", symbol: "Br" },
  { code: "UGX", name: "Ugandan Shilling", flag: "🇺🇬", symbol: "USh" },
  { code: "TZS", name: "Tanzanian Shilling", flag: "🇹🇿", symbol: "TSh" },
  { code: "RWF", name: "Rwandan Franc", flag: "🇷🇼", symbol: "FRw" },
  { code: "BIF", name: "Burundian Franc", flag: "🇧🇮", symbol: "FBu" },
  { code: "XAF", name: "Central African CFA", flag: "🌍", symbol: "FCFA" },
  { code: "XOF", name: "West African CFA", flag: "🌍", symbol: "CFA" },
  { code: "CDF", name: "Congolese Franc", flag: "🇨🇩", symbol: "FC" },
  { code: "AOA", name: "Angolan Kwanza", flag: "🇦🇴", symbol: "Kz" },
  { code: "MZN", name: "Mozambican Metical", flag: "🇲🇿", symbol: "MT" },
  { code: "ZMW", name: "Zambian Kwacha", flag: "🇿🇲", symbol: "ZK" },
  { code: "MWK", name: "Malawian Kwacha", flag: "🇲🇼", symbol: "MK" },
  { code: "BWP", name: "Botswana Pula", flag: "🇧🇼", symbol: "P" },
  { code: "NAD", name: "Namibian Dollar", flag: "🇳🇦", symbol: "$" },
  { code: "SZL", name: "Swazi Lilangeni", flag: "🇸🇿", symbol: "L" },
  { code: "LSL", name: "Lesotho Loti", flag: "🇱🇸", symbol: "L" },
  { code: "MGA", name: "Malagasy Ariary", flag: "🇲🇬", symbol: "Ar" },
  { code: "MUR", name: "Mauritian Rupee", flag: "🇲🇺", symbol: "₨" },
  { code: "SCR", name: "Seychellois Rupee", flag: "🇸🇨", symbol: "₨" },
  { code: "CVE", name: "Cape Verdean Escudo", flag: "🇨🇻", symbol: "$" },
  { code: "GMD", name: "Gambian Dalasi", flag: "🇬🇲", symbol: "D" },
  { code: "GNF", name: "Guinean Franc", flag: "🇬🇳", symbol: "FG" },
  { code: "SLE", name: "Sierra Leonean Leone", flag: "🇸🇱", symbol: "Le" },
  { code: "LRD", name: "Liberian Dollar", flag: "🇱🇷", symbol: "$" },
  { code: "STN", name: "São Tomé Dobra", flag: "🇸🇹", symbol: "Db" },
  { code: "ERN", name: "Eritrean Nakfa", flag: "🇪🇷", symbol: "Nfk" },
  { code: "SSP", name: "South Sudanese Pound", flag: "🇸🇸", symbol: "£" },
  { code: "ZWL", name: "Zimbabwean Dollar", flag: "🇿🇼", symbol: "$" },

  // Americas
  { code: "MXN", name: "Mexican Peso", flag: "🇲🇽", symbol: "$" },
  { code: "BRL", name: "Brazilian Real", flag: "🇧🇷", symbol: "R$" },
  { code: "ARS", name: "Argentine Peso", flag: "🇦🇷", symbol: "$" },
  { code: "CLP", name: "Chilean Peso", flag: "🇨🇱", symbol: "$" },
  { code: "COP", name: "Colombian Peso", flag: "🇨🇴", symbol: "$" },
  { code: "PEN", name: "Peruvian Sol", flag: "🇵🇪", symbol: "S/" },
  { code: "UYU", name: "Uruguayan Peso", flag: "🇺🇾", symbol: "$" },
  { code: "PYG", name: "Paraguayan Guarani", flag: "🇵🇾", symbol: "₲" },
  { code: "BOB", name: "Bolivian Boliviano", flag: "🇧🇴", symbol: "Bs" },
  { code: "VES", name: "Venezuelan Bolívar", flag: "🇻🇪", symbol: "Bs" },
  { code: "GYD", name: "Guyanese Dollar", flag: "🇬🇾", symbol: "$" },
  { code: "SRD", name: "Surinamese Dollar", flag: "🇸🇷", symbol: "$" },
  { code: "CRC", name: "Costa Rican Colón", flag: "🇨🇷", symbol: "₡" },
  { code: "GTQ", name: "Guatemalan Quetzal", flag: "🇬🇹", symbol: "Q" },
  { code: "HNL", name: "Honduran Lempira", flag: "🇭🇳", symbol: "L" },
  { code: "NIO", name: "Nicaraguan Córdoba", flag: "🇳🇮", symbol: "C$" },
  { code: "PAB", name: "Panamanian Balboa", flag: "🇵🇦", symbol: "B/." },
  { code: "DOP", name: "Dominican Peso", flag: "🇩🇴", symbol: "RD$" },
  { code: "CUP", name: "Cuban Peso", flag: "🇨🇺", symbol: "$" },
  { code: "HTG", name: "Haitian Gourde", flag: "🇭🇹", symbol: "G" },
  { code: "JMD", name: "Jamaican Dollar", flag: "🇯🇲", symbol: "$" },
  { code: "TTD", name: "Trinidad & Tobago Dollar", flag: "🇹🇹", symbol: "$" },
  { code: "BBD", name: "Barbadian Dollar", flag: "🇧🇧", symbol: "$" },
  { code: "BSD", name: "Bahamian Dollar", flag: "🇧🇸", symbol: "$" },
  { code: "BZD", name: "Belize Dollar", flag: "🇧🇿", symbol: "BZ$" },
  { code: "XCD", name: "East Caribbean Dollar", flag: "🌎", symbol: "$" },
  { code: "AWG", name: "Aruban Florin", flag: "🇦🇼", symbol: "ƒ" },
  { code: "ANG", name: "Netherlands Antillean Guilder", flag: "🇨🇼", symbol: "ƒ" },
  { code: "KYD", name: "Cayman Islands Dollar", flag: "🇰🇾", symbol: "$" },
  { code: "BMD", name: "Bermudian Dollar", flag: "🇧🇲", symbol: "$" },

  // Pacific
  { code: "FJD", name: "Fijian Dollar", flag: "🇫🇯", symbol: "$" },
  { code: "PGK", name: "Papua New Guinean Kina", flag: "🇵🇬", symbol: "K" },
  { code: "SBD", name: "Solomon Islands Dollar", flag: "🇸🇧", symbol: "$" },
  { code: "TOP", name: "Tongan Paʻanga", flag: "🇹🇴", symbol: "T$" },
  { code: "WST", name: "Samoan Tala", flag: "🇼🇸", symbol: "T" },
  { code: "VUV", name: "Vanuatu Vatu", flag: "🇻🇺", symbol: "Vt" },
  { code: "XPF", name: "CFP Franc", flag: "🇵🇫", symbol: "₣" },
];

export const POPULAR_PAIRS: Array<[string, string]> = [
  ["USD", "EUR"],
  ["USD", "GBP"],
  ["USD", "JPY"],
  ["EUR", "GBP"],
  ["USD", "CAD"],
  ["USD", "AUD"],
  ["GBP", "EUR"],
  ["USD", "INR"],
  ["USD", "AED"],
  ["USD", "SAR"],
  ["USD", "EGP"],
  ["EUR", "MAD"],
];

export function getCurrency(code: string): Currency | undefined {
  return CURRENCIES.find((c) => c.code === code.toUpperCase());
}
